### PR TITLE
auto packaging on tag

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by jbraswell** [comment]
Basically the contents need to mirror BMLT-Root-Server.zip in the root of the repo. Then we can just delete that zip from source control, and update the references to it on bmlt.app.

**Comment by jbraswell** [comment]
I’m happy to continue this work if you don’t have the time. My last day at my job is Thursday, and then I have two weeks to work on whatever.

**Comment by radius314** [comment]
just pushed a change that will do as such

**Comment by radius314** [comment]
btw I may need to do a series of tweaks here... I didn't go as far as to test this completely on my fork.

**Comment by jbraswell** [comment]
Does merging this make testing any easier for you, or are you fine working through issues in your fork?

**Comment by radius314** [comment]
yeah i need to merge

**Comment by radius314** [comment]
i can try to work in a branch on this main repo

**Comment by radius314** [comment]
would be good to have an initial sense of pass/fail though.

**Comment by jbraswell** [comment]
Cool. My preference is to work in a non-master branch, but I’m also fine with just merging to master as long as the work is pushed to completion (I know it will be). Use your best judgment. As an owner you can merge PRs on this repo, right?

**Pull request merged**
