### PR TITLE
WIP: Add unpublished reason

### PR DESCRIPTION
**Pull request by jbraswell**
- [x] Add unpublished reason to UI
- [x] Handle unpublished reason on the backend
- [ ] Test iOS admin app
- [ ] Determine appropriate canned responses for unpublished reason
- [ ] Add `unpublished_reason` column to the NAWS csv
- [ ] Add message to the UI explaining that unpublished should not be used to indicate a meeting has permanently closed.
- [ ] Add strings to translation files
- [ ] Make sure cache busting is added to the js file before merging

Closes https://github.com/bmlt-enabled/bmlt-root-server/issues/82

### CODE REVIEW

**Comment by pjaudiomv** [comment]
Loss of meeting facility or temporary loss

**Comment by jbraswell** [comment]
@pjaudiomv I think the core functionality here is mostly done. Could us some help with testing. I think I've tested most of it myself, but one gap I know about is the iOS app.

**Comment by pjaudiomv** [comment]
if a meeting is already unpublished in the database the `"Save the Changes to This Meeting"` button is white implying theres been a change, if you then try to go to another meeting it asks you `"You are currently editing another meeting. Do you want to lose all changes in that meeting?"`even though I didnt make any changes. If I do select an `Unpublished Reason` and hit save it still does this, even if I go to another meeting and come back.

**Comment by pjaudiomv** [comment]
another weird thing. the email_contact field in the database was always NULL but any one that i've edited turns to just empty even though i never edited that field.

Screen Shot 2019-07-07 at 7 47 04 PM

**Comment by ChrisMarshallNY** [comment]
The "dirty flag" issue is familiar.
The JS does a pretty "brute force" test to see if a meeting  has changed; just a simple string test.
If there is ANY difference between the current meeting string, and the initial JSON object, then it flags it as changed. This includes things like the order of data members in the serialized object.

**Pull request closed without merging**
