### PR TITLE
Make semantic administration default #169

### PR DESCRIPTION
**Pull request by pjaudiomv**
#169

### CODE REVIEW

**Comment by pjaudiomv** [comment]
I tested this and works fine

**Comment by jbraswell** [comment]
When you tested this did it work fine?

**Comment by pjaudiomv** [comment]
yea dude how many time do you need me to say it lol

**Comment by jbraswell** [comment]
You don’t need to set `checked="checked"`. You can just have the `checked` attribute without setting it to anything. See https://www.w3schools.com/tags/att_input_checked.asp. 

I think removing the setting altogether might be better, though. I don’t think there’s much point in even having the option to disable the semantic UI. Thoughts?

**Comment by pjaudiomv** [comment]
yes i know this, but thats how Meetings Are Considerd "CLOSED" by Default setting did it so i was just staying consistent. that must of been older code because there are other places where it is just checked

**Comment by pjaudiomv** [comment]
note that this doesn't disable the semantic ui it disables the semantic ADMIN ui.

**Comment by jbraswell** [comment]
That’s what I said bro look at my comment

**Comment by jbraswell** [comment]
I’m totes fine with this getting merged. Up to you if you wanna do more here.

**Comment by pjaudiomv** [comment]
yea i kind of just assume leave it there may be other tinfoil hats that want the option to disable.

**Comment by jbraswell** [comment]
Works for me

**Pull request merged**
