### PR TITLE
passing gkey in as env var

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Comment by jbraswell** [comment]
I think if we merged this right now it'd make the CD hang, you'll need to find a way to pass in the variable to the terraform on each run before we merge this.

**Comment by pjaudiomv** [comment]
I added the env var to travis so it should be available as soon as container spins up, `TF_VAR_GOOGLE_API_KEY`

**Comment by jbraswell** [comment]
Will you add the variable to a `variables.tf` file instead?

**Comment by pjaudiomv** [comment]
done

**Comment by jbraswell** [comment]
If you say something nice about me, I'll merge this

**Comment by pjaudiomv** [comment]
I miss the way you smell, which is good.

**Pull request merged**
