### PR TITLE
automate setting of release notes

### PR DESCRIPTION
**Pull request by pjaudiomv**
this will automatically add release notes to releases using this tool https://github.com/bmlt-enabled/release-notes-tool/

### CODE REVIEW

**Comment by pjaudiomv** [comment]
Bro

**Comment by jbraswell** [comment]
Can I close this

**Comment by pjaudiomv** [comment]
I'd rather we merge it instead

**Comment by jbraswell** [comment]
I wonder if it still works

**Comment by pjaudiomv** [comment]
I feel like it should :/

**Comment by jbraswell** [comment]
Sometimes I feel like the earth is flat

**Comment by pjaudiomv** [comment]
I tested it on a test repo

**Comment by pjaudiomv** [comment]
Space is fake

**Pull request merged**
