### PR TITLE
fix for JSONP mime type #167

### PR DESCRIPTION
**Pull request by pjaudiomv**
ref #167

### CODE REVIEW

**Comment by jbraswell** [comment]
Seems reasonable. Did you test the tests?

**Comment by pjaudiomv** [comment]
yea looks good https://www.nerna.org/main_server/client_interface/jsonp/?switcher=GetServiceBodies&callback=rawr_im_a_dinasaur

**Comment by jbraswell** [comment]
merge that shit

**Comment by radius314** [comment]
👍

**Pull request merged**
