### PR TITLE
update composer for latest sat base class

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Comment by pjaudiomv** [comment]
I did composer update, was i supposed to do anything else?

**Comment by jbraswell** [comment]
This is perfect. Make sure you test that the html endpoint UI works with this version of the base class and then we’re good.

**Comment by pjaudiomv** [comment]
works fine, like a glove

**Comment by jbraswell** [comment]
Make like a tree and get out of here

**Pull request merged**
