### PR TITLE
adding server version to login page

### PR DESCRIPTION
**Pull request by pjaudiomv**
@radius314  had suggested having server version on login screen, I often had thought/wished it would be there too. now it can be....  this would appear the same as when authenticated only white

### CODE REVIEW

**Comment by pjaudiomv** [comment]
could go bottom right too idk

**Comment by pjaudiomv** [comment]
Screen Shot 2019-07-23 at 11 32 20 PM
Screen Shot 2019-07-23 at 11 29 44 PM

**Comment by pjaudiomv** [comment]
Bottoms better

**Comment by radius314** [comment]
How’s it look on mobile?

**Comment by radius314** [comment]
It could also be centered under the log in button.

**Comment by pjaudiomv** [comment]
it actually looks better on top right for mobile

**Pull request merged**
