### PR TITLE
bump crouton

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Comment by dgershman** [comment]
might as well target 3.12.6

**Comment by pjaudiomv** [comment]
> might as well target 3.12.6

done

**Review by dgershman — APPROVED** [review]

**Review by jbraswell — APPROVED** [review]
As long as it's tested!

**Comment by pjaudiomv** [comment]
> 

thats what prod is for

**Comment by pjaudiomv** [comment]
Screen Shot 2021-11-22 at 8 08 30 PM

**Comment by dgershman** [comment]
so much agile

**Pull request merged**
