### PR TITLE
fixing ulimit issue

### PR DESCRIPTION
**Pull request by radius314**
Attempting to address this issue in the failing ECS container.

image

### CODE REVIEW

**Comment by jbraswell** [comment]
What is the ulimit issue? How does it present itself, what is the impact?

**Comment by radius314** [comment]
The container died.  I looked at the Cloudwatch logs and saw this. 

https://github.com/bmlt-enabled/bmlt-root-server/pull/315#issue-447948535

**Comment by radius314** [comment]
I am referencing this as my attempt to address this https://stackoverflow.com/questions/57486473/ulimit-error-setting-limit-operation-not-permitted-using-apachectl-in-cont.

**Comment by jbraswell** [comment]
In the logs, it looks like Apache is trying and failing to set the ulimit. Does having the ECS agent set it per the proposed task definition change prevent Apache from making the calls to set the ulimit?

**Comment by radius314** [comment]
My thought was that it was trying to set it to `null`.  I honestly have no idea.

**Comment by jbraswell** [comment]
Okay. If it's tested, let's merge it. I'd like to a avoid merging things to master that we aren't sure if they work.

**Comment by radius314** [comment]
How can I test this ahead of merging to master?  I see an unstable ECS configuration, do i merge to unstable to try things out there?

**Comment by jbraswell** [comment]
You could  do that, or you could manually modify the task definition (terraform will revert it if it doesn't work), or you could run the terraform locally with the change to see.

**Comment by jbraswell** [comment]
I am not sure that's even a fatal error. It looks like apache still started and serves traffic just fine.

image

The real error is `/tmp/start-bmlt.sh: line 39: [: too many arguments`.

**Comment by radius314** [comment]
I'm wondering if it's the default shell and if we should be explicit with a shebang.

**Comment by jbraswell** [comment]
`if [ ! -z $DO_NOT_FORCE_PORT -a "$DO_NOT_FORCE_PORT" == "true" ]`

I wonder if `$DO_NOT_FORCE_PORT` needs to be quoted like this: `if [ ! -z "$DO_NOT_FORCE_PORT" -a "$DO_NOT_FORCE_PORT" == "true" ]`

**Comment by radius314** [comment]
testing this theory now

**Comment by jbraswell** [comment]
Pretty sure if you just surround $DO_NOT_FORCE_PORT in double quotes it'll fix it.

**Comment by jbraswell** [comment]
Looks like it's been broken for a while?

**Pull request closed without merging**
