### PR TITLE
skip docs if not master

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by pjaudiomv** [comment]
whats the difference between the two

**Comment by jbraswell** [comment]
I am not convinced that we don't want to build the docs on non-master. Seems useful to know if the build is broken. It doesn't deploy them.

**Comment by pjaudiomv** [comment]
how is `on branch: master` different than `if: branch = master`

**Comment by radius314** [comment]
Is the placement of the conditional.  One is on the job lifecycle the other is on the entire stage.

**Comment by pjaudiomv** [comment]
oh shoot yea thanks, probably would of figured out looking at whole file

**Pull request closed without merging**
