### PR TITLE
 leading zero patch new pull

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Comment by radius314** [comment]
those two commits by me should not be there

**Comment by pjaudiomv** [comment]
Do I need to git rebase -i HEAD or something like that how do I remove a commit

**Comment by pjaudiomv** [comment]
not sure how to commit the readme and not have it conflict unless we trash this pull request too and i rebase then make the changes and do another pull request that should def resolve fine then

**Comment by pjaudiomv** [comment]
i think i figured it out, talking to myself can really help sometimes. I also think i have a better understanding of git and trees and branches and leaves and flowers

**Comment by radius314** [comment]
I did a squash merge.

**Pull request merged**
