### PR TITLE
matching to yap font, better on the eyes

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by radius314** [comment]
image

**Comment by radius314** [comment]
image

**Comment by radius314** [comment]
image

**Comment by jbraswell** [comment]
Change both to comic sans? Wingdings?

@pjaudiomv thoughts?

**Comment by radius314** [comment]
image

**Comment by radius314** [comment]
Here is Comic Sans:

image

**Comment by radius314** [comment]
image

**Comment by radius314** [comment]
Here's Wingdings

image

**Comment by radius314** [comment]
image

**Comment by radius314** [comment]
croutonjs wingdings

image

**Comment by pjaudiomv** [comment]
How about dingbats

**Review by jbraswell — APPROVED** [review]

**Pull request merged**
